import { Platform, StyleSheet } from 'react-native';
import { CLINICAL_COLORS, CLINICAL_TINTS } from '../../lib/clinical-visuals';

const cardShadow =
  Platform.select({
    ios: {
      shadowColor: '#182B36',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
    },
    android: {
      elevation: 7,
    },
    default: {},
  }) ?? {};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CLINICAL_COLORS.background,
  },
  backgroundGradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eyebrow: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  pageTitle: {
    marginTop: 2,
    color: CLINICAL_COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  heroCard: {
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_COLORS.panel,
    ...cardShadow,
  },
  heroTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 25,
    lineHeight: 33,
    fontWeight: '800',
  },
  heroDescription: {
    marginTop: 10,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 14,
    lineHeight: 21,
  },
  heroMetaRow: {
    marginTop: 20,
    flexDirection: 'row',
    gap: 12,
  },
  heroMetaCard: {
    flex: 1,
    minHeight: 92,
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  heroMetaValue: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  heroMetaLabel: {
    marginTop: 8,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  modeSection: {
    marginTop: 22,
    marginHorizontal: 20,
  },
  modeSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  modeSectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  modeSectionSubtitle: {
    marginTop: 6,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  modeSectionPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  modeSectionPillText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  modeGrid: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  modeCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 216,
    borderRadius: 22,
    padding: 14,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    gap: 8,
    ...cardShadow,
  },
  modeCardWide: {
    flex: 1,
  },
  modeCardActive: {
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_TINTS.accentSurface,
  },
  modeCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  modeOrderWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  modeOrderText: {
    color: CLINICAL_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  modeStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  modeStatusBadgeActive: {
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  modeStatusBadgeText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 10,
    fontWeight: '700',
  },
  modeStatusBadgeTextActive: {
    color: CLINICAL_COLORS.text,
  },
  modeIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  modeEyebrow: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 10,
    letterSpacing: 0.8,
  },
  modeTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  modeDescription: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
  },
  modeFooter: {
    marginTop: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: CLINICAL_COLORS.border,
  },
  modeCtaText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  modeCtaTextActive: {
    color: CLINICAL_COLORS.accentStrong,
  },
  modeCurrentCard: {
    marginTop: 14,
    borderRadius: 20,
    padding: 16,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  modeCurrentLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.0,
  },
  modeCurrentTitle: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  modeCurrentText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  formStack: {
    marginTop: 22,
    marginHorizontal: 20,
    gap: 14,
  },
  sectionCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  sectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  sectionSubtitle: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  fieldBlock: {
    marginTop: 16,
  },
  fieldHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  fieldLabel: {
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  fieldHint: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  input: {
    marginTop: 10,
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: CLINICAL_COLORS.background,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
  },
  textarea: {
    minHeight: 108,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  rowItem: {
    flex: 1,
  },
  choiceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
  },
  choiceChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.background,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  choiceChipActive: {
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  choiceChipText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    fontWeight: '700',
  },
  choiceChipTextActive: {
    color: CLINICAL_COLORS.text,
  },
  scoreBlock: {
    marginTop: 16,
  },
  scoreRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  scoreChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_COLORS.background,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  scoreChipActive: {
    backgroundColor: CLINICAL_COLORS.accentStrong,
    borderColor: CLINICAL_COLORS.accentStrong,
  },
  scoreChipText: {
    color: CLINICAL_COLORS.text,
    fontSize: 13,
    fontWeight: '700',
  },
  scoreChipTextActive: {
    color: '#FFFFFF',
  },
  scoreHintWrap: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  scoreHintChip: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  scoreHintText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    fontWeight: '600',
  },
  uploadButton: {
    marginTop: 16,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  uploadButtonText: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
  },
  tipList: {
    marginTop: 14,
    gap: 10,
  },
  tipItem: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  tipText: {
    flex: 1,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  submitButton: {
    marginTop: 6,
    minHeight: 56,
    borderRadius: 20,
    backgroundColor: CLINICAL_COLORS.accentStrong,
    alignItems: 'center',
    justifyContent: 'center',
    ...cardShadow,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: 'rgba(248, 242, 234, 0.76)',
  },
  loadingText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
});
