import { Platform, StyleSheet } from 'react-native';
import { CLINICAL_COLORS, CLINICAL_TINTS } from '../../lib/clinical-visuals';

const cardShadow =
  Platform.select({
    ios: {
      shadowColor: '#182B36',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
    },
    android: {
      elevation: 7,
    },
    default: {},
  }) ?? {};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CLINICAL_COLORS.background,
  },
  backgroundGradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eyebrow: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  pageTitle: {
    marginTop: 2,
    color: CLINICAL_COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: CLINICAL_COLORS.accentStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  section: {
    marginHorizontal: 20,
    marginBottom: 22,
  },
  sectionHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  inlineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  inlineActionText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  heroCard: {
    padding: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_COLORS.panel,
    ...cardShadow,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  riskChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(248, 242, 234, 0.74)',
  },
  riskDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  riskText: {
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryAction: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  secondaryActionText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  heroTitle: {
    marginTop: 18,
    color: CLINICAL_COLORS.text,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '800',
  },
  heroText: {
    marginTop: 10,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 14,
    lineHeight: 21,
  },
  heroMetrics: {
    marginTop: 18,
    flexDirection: 'row',
    gap: 12,
  },
  metricCard: {
    flex: 1,
    minHeight: 92,
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  metricValue: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  metricLabel: {
    marginTop: 8,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  sectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  sectionSubtitle: {
    marginTop: 6,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  stateWrap: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    alignItems: 'center',
    gap: 12,
  },
  stateText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  retryButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.accentStrong,
  },
  retryText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  reviewItem: {
    marginTop: 10,
    borderRadius: 18,
    padding: 14,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    ...cardShadow,
  },
  reviewText: {
    flex: 1,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  quickActionRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 12,
  },
  quickActionCard: {
    flex: 1,
    borderRadius: 20,
    padding: 16,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    gap: 10,
    ...cardShadow,
  },
  quickActionStandalone: {
    marginTop: 12,
  },
  quickActionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  quickActionText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  cardHeading: {
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  pillWrap: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  pillText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  monitorDivider: {
    height: 1,
    backgroundColor: CLINICAL_COLORS.border,
    marginVertical: 16,
  },
  changeRow: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  changeCopy: {
    flex: 1,
  },
  changeTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  changeDetail: {
    marginTop: 6,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  changeBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  changeBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  insightGrid: {
    marginTop: 2,
    gap: 12,
  },
  insightCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  insightTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  insightTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  insightDate: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  insightSummary: {
    marginTop: 10,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  metricWrap: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricPill: {
    minWidth: 112,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  metricPillLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  metricPillValue: {
    marginTop: 4,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  visualizationChartStack: {
    marginTop: 2,
    gap: 12,
  },
  visualizationSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  visualizationChartCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  visualizationChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  visualizationChartHeaderMain: {
    flex: 1,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  toggleChip: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleChipActive: {
    backgroundColor: CLINICAL_COLORS.accentStrong,
    borderColor: CLINICAL_COLORS.accentStrong,
  },
  toggleChipText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  toggleChipTextActive: {
    color: '#FFFFFF',
  },
  visualizationChartTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  visualizationChartValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  visualizationChartSummary: {
    marginTop: 12,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  visualizationChartHint: {
    marginTop: 8,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  chartWrap: {
    marginTop: 12,
    marginHorizontal: -2,
    borderRadius: 16,
    overflow: 'hidden',
    alignItems: 'center',
  },
  chart: {
    borderRadius: 16,
  },
  chartEmpty: {
    marginTop: 12,
    minHeight: 100,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_TINTS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.borderSubtle,
  },
  timelineSectionCard: {
    marginTop: 2,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineRail: {
    width: 18,
    alignItems: 'center',
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: CLINICAL_COLORS.accentStrong,
    marginTop: 8,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    marginTop: 6,
    marginBottom: -10,
    backgroundColor: CLINICAL_TINTS.accentBorder,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 18,
  },
  timelineHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  timelineTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  timelineTagText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  timelineTime: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  timelineTitle: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  timelineText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  systemStack: {
    gap: 12,
  },
  systemCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  systemCardTop: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  systemIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  systemCardCopy: {
    flex: 1,
  },
  systemBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  systemStateBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  systemStateBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  systemCoverageChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  systemCoverageChipText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  systemTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  systemTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  systemDate: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  systemSummary: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  systemMetaGrid: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  systemMetaCard: {
    flex: 1,
    borderRadius: 16,
    padding: 12,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  systemMetaLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  systemMetaValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  systemMetricHeroGrid: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  systemMetricHeroCard: {
    width: '47%',
    minHeight: 84,
    padding: 14,
    borderRadius: 18,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  systemMetricHeroLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  systemMetricHeroValue: {
    marginTop: 10,
    color: CLINICAL_COLORS.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
  },
  systemSectionStack: {
    marginTop: 16,
    gap: 14,
  },
  systemSectionBlock: {
    borderTopWidth: 1,
    borderTopColor: CLINICAL_COLORS.border,
    paddingTop: 14,
  },
  systemSectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  systemExpandAction: {
    marginTop: 14,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  systemExpandText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  systemMetricGrid: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  systemMetricCard: {
    width: '47%',
    minHeight: 74,
    padding: 12,
    borderRadius: 16,
    backgroundColor: CLINICAL_COLORS.panelMuted,
  },
  systemMetricLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  systemMetricValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
  },
  emptyText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: 'rgba(248, 242, 234, 0.76)',
  },
  loadingText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
});
