import { Platform, StyleSheet } from 'react-native';
import { CLINICAL_COLORS, CLINICAL_TINTS } from '../../lib/clinical-visuals';

const cardShadow =
  Platform.select({
    ios: {
      shadowColor: '#182B36',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
    },
    android: {
      elevation: 7,
    },
    default: {},
  }) ?? {};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CLINICAL_COLORS.background,
  },
  backgroundGradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eyebrow: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  pageTitle: {
    marginTop: 2,
    color: CLINICAL_COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: CLINICAL_COLORS.accentStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  section: {
    marginHorizontal: 20,
    marginBottom: 22,
  },
  heroCard: {
    padding: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_COLORS.panel,
    ...cardShadow,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  riskChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(248, 242, 234, 0.74)',
  },
  riskDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  riskText: {
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryAction: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  secondaryActionText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  heroTitle: {
    marginTop: 18,
    color: CLINICAL_COLORS.text,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '800',
  },
  heroText: {
    marginTop: 10,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 14,
    lineHeight: 21,
  },
  heroMetrics: {
    marginTop: 18,
    flexDirection: 'row',
    gap: 12,
  },
  metricCard: {
    flex: 1,
    minHeight: 92,
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  metricValue: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  metricLabel: {
    marginTop: 8,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  sectionHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  stateWrap: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    alignItems: 'center',
    gap: 12,
  },
  stateText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  retryButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.accentStrong,
  },
  retryText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  reviewItem: {
    marginTop: 10,
    borderRadius: 18,
    padding: 14,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    ...cardShadow,
  },
  reviewText: {
    flex: 1,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  quickActionRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 12,
  },
  quickActionCard: {
    flex: 1,
    borderRadius: 20,
    padding: 16,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    gap: 10,
    ...cardShadow,
  },
  quickActionStandalone: {
    marginTop: 12,
  },
  quickActionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  quickActionText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  cardHeading: {
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  pillWrap: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  pillText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  monitorDivider: {
    height: 1,
    backgroundColor: CLINICAL_COLORS.border,
    marginVertical: 16,
  },
  changeRow: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  changeCopy: {
    flex: 1,
  },
  changeTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  changeDetail: {
    marginTop: 6,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  changeBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  changeBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  toggleChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.panel,
  },
  toggleChipActive: {
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  toggleChipText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  toggleChipTextActive: {
    color: CLINICAL_COLORS.text,
  },
  focusWrap: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  focusTag: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  focusTagText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  trendGrid: {
    gap: 12,
  },
  trendCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  trendTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  trendValue: {
    marginTop: 10,
    color: CLINICAL_COLORS.accentStrong,
    fontSize: 22,
    fontWeight: '800',
  },
  trendText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineRail: {
    width: 18,
    alignItems: 'center',
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: CLINICAL_COLORS.accentStrong,
    marginTop: 8,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    marginTop: 6,
    marginBottom: -10,
    backgroundColor: CLINICAL_TINTS.accentBorder,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 18,
  },
  timelineHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  timelineTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  timelineTagText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  timelineTime: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  timelineTitle: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  timelineText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  monitorGrid: {
    gap: 12,
  },
  monitorCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    flexDirection: 'row',
    gap: 12,
    ...cardShadow,
  },
  monitorIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  monitorCopy: {
    flex: 1,
  },
  monitorTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  monitorDate: {
    marginTop: 4,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  monitorText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  emptyText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: 'rgba(248, 242, 234, 0.76)',
  },
  loadingText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
});
