/**
 * Draft a structured log entry from one sentence of plain Chinese.
 *
 * Why this is not an orchestrator tool
 * ------------------------------------
 * The obvious shape would be a `draft_my_log` tool in the registry.
 * It isn't, for two reasons. First, every existing tool wraps a
 * *retriever* and returns chunks for the context builder; drafting
 * retrieves nothing, so it would be a permanent special case in a
 * pipeline whose uniformity is what makes the redaction contract
 * checkable. Second — and this is the real one — a tool is something
 * the planner may call whenever it likes. Structuring a medical log
 * entry is not a thing that should ever happen as a side effect of a
 * chat turn; it happens because the patient pressed 记一笔.
 *
 * So it's a single-shot, single-purpose call with its own endpoint.
 *
 * What it is allowed to do
 * ------------------------
 * Produce a draft. Nothing here writes to the database, and the
 * returned object is deliberately shaped to *pre-fill the existing
 * entry form* rather than to be persisted directly: the patient sees
 * every field, edits what's wrong, and the save goes through the same
 * validated `POST /profiles/me/*` handlers a hand-typed entry uses.
 * The model's output never reaches the database except through a
 * human who looked at it.
 *
 * Anything the model returns that doesn't validate is dropped, not
 * repaired. A clamped-to-range number would be indistinguishable from
 * one the patient actually said, and an invented measurement in a
 * disease-progression record is worse than a blank field.
 */

import { z } from 'zod';

import type { AppLogger } from '../../../config/logger.js';
import type { ILLMProvider } from '../llm/base.js';

/** Event types a patient can plausibly describe out loud.
 *  `uploaded_report` is excluded on purpose — it's system-generated by
 *  the document pipeline, never something someone says happened. */
const DRAFTABLE_EVENT_TYPES = [
  'fall',
  'new_foot_drop',
  'new_arm_raise_difficulty',
  'new_breathing_discomfort',
  'started_afo',
  'started_wheelchair',
  'started_niv',
  'other',
] as const;

const nullableNumber = (schema: z.ZodNumber) => z.union([schema, z.null()]).optional().catch(null);

/** Every field is independently `.catch()`-guarded so one bad value
 *  costs that field only. A model that nails the fall count but
 *  hallucinates a stair time should still save the patient the typing
 *  it got right. */
const followupDraftSchema = z.object({
  stairClimbSeconds: nullableNumber(z.number().min(0).max(600)),
  sleepScore: nullableNumber(z.number().int().min(0).max(10)),
  fallCount: nullableNumber(z.number().int().min(0).max(50)),
  activityNote: z
    .union([z.string().max(500), z.null()])
    .optional()
    .catch(null),
});

/** Both classification fields are nullable for the same reason the
 *  numbers are. `.catch('other')` also fires on a *missing* key, so a
 *  model that said nothing about the type was indistinguishable from
 *  one that said「其他」— and the client, unable to tell them apart,
 *  had to overwrite whatever the patient had already picked by hand.
 *  A `fall`/`severe` the patient chose themselves being silently
 *  rewritten to `other`/`moderate` is exactly the "repaired" value
 *  this file's header says we don't ship. Null means "not heard". */
const eventDraftSchema = z.object({
  eventType: z.enum(DRAFTABLE_EVENT_TYPES).nullable().optional().catch(null),
  severity: z.enum(['mild', 'moderate', 'severe']).nullable().optional().catch(null),
  occurredAt: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/)
    .nullable()
    .optional()
    .catch(null),
  description: z.string().max(500).nullable().optional().catch(null),
});

const draftEnvelopeSchema = z.object({
  understanding: z.string().max(200).nullable().optional().catch(null),
  followup: followupDraftSchema.nullable().optional().catch(null),
  event: eventDraftSchema.nullable().optional().catch(null),
});

export type FollowupDraft = z.infer<typeof followupDraftSchema>;
export type EventDraft = z.infer<typeof eventDraftSchema>;

export interface DraftLogResult {
  /** One-line restatement in the patient's own terms, rendered above
   *  the form so they can check the understanding before the numbers. */
  understanding: string | null;
  followup: FollowupDraft | null;
  event: EventDraft | null;
}

export const EMPTY_DRAFT: DraftLogResult = {
  understanding: null,
  followup: null,
  event: null,
};

const SYSTEM_PROMPT = `你是 FSHD 患者记录助手。把用户的一句话整理成结构化草稿。

【只输出 JSON】
输出一个 JSON 对象，不要有任何解释文字，不要用 markdown 代码块。结构：
{
  "understanding": "用一句话复述你的理解（20 字以内）",
  "followup": { "stairClimbSeconds": 数字或null, "sleepScore": 0-10整数或null, "fallCount": 整数或null, "activityNote": "字符串或null" } 或 null,
  "event": { "eventType": "...或null", "severity": "mild|moderate|severe 或 null", "occurredAt": "YYYY-MM-DD", "description": "字符串" } 或 null
}

【eventType 取值】
fall（跌倒）、new_foot_drop（新出现足下垂）、new_arm_raise_difficulty（新出现抬臂困难）、
new_breathing_discomfort（新出现呼吸不适）、started_afo（开始用踝足矫形器）、
started_wheelchair（开始用轮椅）、started_niv（开始无创通气）、other（其他）

【硬性规则】
- understanding 等文本字段只写纯文本，不要 Markdown：这些字段会显示在一行提示条里，标记符号会原样出现。
- 用户没说的数值一律填 null。绝对不要估算、不要补全、不要用"一般来说"的常见值。
- eventType / severity 同理：听不出是哪一类、或用户没说轻重，就填 null。不要用 other / moderate 兜底——用户可能已经自己选好了，填了就会把他选的覆盖掉。
- 用户只描述日常状态 → 只填 followup，event 为 null。
- 用户描述了一件发生的事（摔倒、新症状、开始用辅具）→ 填 event；如果同时提到日常数值，两个都填。
- 日期没说就填 null，不要猜。
- 不做医学判断，不给建议，description 只复述用户说的事实。`;

/** Models wrap JSON in ```json fences roughly half the time no matter
 *  how firmly the prompt says not to. Strip them rather than failing a
 *  response that is otherwise exactly right. */
const extractJsonObject = (raw: string): unknown => {
  const withoutFences = raw
    .replace(/^\s*```(?:json)?/i, '')
    .replace(/```\s*$/, '')
    .trim();

  const start = withoutFences.indexOf('{');
  const end = withoutFences.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) return null;

  try {
    return JSON.parse(withoutFences.slice(start, end + 1)) as unknown;
  } catch {
    return null;
  }
};

/** True when a followup draft carries nothing worth pre-filling — the
 *  model answered but found no numbers. Returning it anyway would show
 *  the patient an empty "AI 整理好了" card, which reads as a failure
 *  dressed as a success. */
const isEmptyFollowup = (draft: FollowupDraft | null | undefined): boolean =>
  !draft ||
  (draft.stairClimbSeconds == null &&
    draft.sleepScore == null &&
    draft.fallCount == null &&
    !draft.activityNote?.trim());

/** Same guard for the event half. It only became possible once the
 *  two enums stopped defaulting: `{"event":{}}` used to validate into
 *  a complete-looking `{eventType:'other',severity:'moderate'}`, which
 *  the client accepted as a real event and pre-filled — pulling the
 *  *previous* saved event's description in beside it, so a hallucinated
 *  event arrived wearing the text of last month's fall. */
const isEmptyEvent = (draft: EventDraft | null | undefined): boolean =>
  !draft ||
  (draft.eventType == null &&
    draft.severity == null &&
    !draft.occurredAt &&
    !draft.description?.trim());

export interface DraftLogOptions {
  llm: ILLMProvider;
  logger: AppLogger;
  requestId: string;
  signal?: AbortSignal;
}

export const draftLogFromText = async (
  text: string,
  opts: DraftLogOptions,
): Promise<DraftLogResult> => {
  const response = await opts.llm.chat({
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: text },
    ],
    // Extraction, not conversation: near-zero temperature so the same
    // sentence drafts the same way twice.
    temperature: 0.1,
    maxTokens: 600,
    requestId: opts.requestId,
    signal: opts.signal,
  });

  const parsedJson = extractJsonObject(response.content ?? '');
  if (parsedJson === null) {
    opts.logger.warn({ requestId: opts.requestId }, 'draft-log: model did not return JSON');
    return EMPTY_DRAFT;
  }

  const parsed = draftEnvelopeSchema.safeParse(parsedJson);
  if (!parsed.success) {
    opts.logger.warn(
      { requestId: opts.requestId, issues: parsed.error.issues.length },
      'draft-log: envelope failed validation',
    );
    return EMPTY_DRAFT;
  }

  const followup = isEmptyFollowup(parsed.data.followup) ? null : (parsed.data.followup ?? null);
  const event = isEmptyEvent(parsed.data.event) ? null : (parsed.data.event ?? null);

  return {
    understanding: parsed.data.understanding?.trim() || null,
    followup,
    event,
  };
};
