import { Platform, StyleSheet } from 'react-native';
import { CLINICAL_COLORS, CLINICAL_TINTS } from '../../lib/clinical-visuals';

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 30,
  },
  android: {
    elevation: 8,
  },
});

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CLINICAL_COLORS.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: CLINICAL_COLORS.overlay,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyebrow: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.2,
  },
  headerTitle: {
    marginTop: 2,
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  heroCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    marginBottom: 14,
    ...cardShadow,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  kindPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentStrong,
  },
  kindPillText: {
    color: CLINICAL_COLORS.accentStrong,
    fontSize: 12,
    fontWeight: '700',
  },
  statusText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  heroTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 28,
  },
  heroDescription: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  highlightGrid: {
    marginTop: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  highlightItem: {
    width: '47%',
    padding: 12,
    borderRadius: 16,
    backgroundColor: CLINICAL_COLORS.panelMuted,
  },
  highlightLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  highlightValue: {
    marginTop: 6,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '700',
  },
  card: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    marginBottom: 14,
    ...cardShadow,
  },
  sectionHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  toggleChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.overlay,
  },
  toggleChipActive: {
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  toggleChipText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  toggleChipTextActive: {
    color: CLINICAL_COLORS.text,
  },
  tagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  summaryTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSurface,
  },
  summaryTagText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
  },
  structuredGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  structuredSection: {
    marginTop: 14,
  },
  structuredSectionTitle: {
    marginBottom: 10,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  structuredItem: {
    width: '47%',
    padding: 12,
    borderRadius: 16,
    backgroundColor: CLINICAL_COLORS.panelMuted,
  },
  structuredLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  structuredValue: {
    marginTop: 6,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  systemStack: {
    marginTop: 12,
    gap: 12,
  },
  systemCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  systemCardTop: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  systemIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  systemCardCopy: {
    flex: 1,
  },
  systemBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  systemStateBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  systemStateBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  systemCoverageChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  systemCoverageChipText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  systemTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  systemTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  systemDate: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  systemSummary: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  systemMetaGrid: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  systemMetaCard: {
    flex: 1,
    borderRadius: 16,
    padding: 12,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  systemMetaLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  systemMetaValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  systemMetricHeroGrid: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  systemMetricHeroCard: {
    width: '47%',
    minHeight: 84,
    padding: 14,
    borderRadius: 18,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  systemMetricHeroLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  systemMetricHeroValue: {
    marginTop: 10,
    color: CLINICAL_COLORS.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
  },
  systemSectionStack: {
    marginTop: 16,
    gap: 14,
  },
  systemSectionBlock: {
    borderTopWidth: 1,
    borderTopColor: CLINICAL_COLORS.border,
    paddingTop: 14,
  },
  systemSectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  systemMetricGrid: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  systemMetricCard: {
    width: '47%',
    minHeight: 74,
    padding: 12,
    borderRadius: 16,
    backgroundColor: CLINICAL_COLORS.panelMuted,
  },
  systemMetricLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  systemMetricValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
  },
  systemExpandAction: {
    marginTop: 14,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  systemExpandText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  button: {
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_COLORS.accent,
  },
  buttonDisabled: {
    opacity: 0.72,
  },
  buttonText: {
    color: CLINICAL_COLORS.text,
    fontWeight: '800',
  },
  dangerCard: {
    borderColor: CLINICAL_TINTS.dangerBorder,
  },
  dangerButton: {
    marginTop: 14,
    backgroundColor: CLINICAL_COLORS.danger,
  },
  dangerButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  summaryText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 14,
    lineHeight: 21,
  },
  smallText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  codeBlock: {
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  codeText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    lineHeight: 16,
  },
  toggleLink: {
    marginTop: 8,
  },
  toggleLinkText: {
    color: CLINICAL_COLORS.accent,
    fontSize: 13,
    fontWeight: '700',
  },
  inlineState: {
    marginTop: 4,
    alignItems: 'center',
    gap: 8,
  },
});
