import { Platform, StyleSheet } from 'react-native';
import { CLINICAL_COLORS, CLINICAL_TINTS } from '../../lib/clinical-visuals';

const cardShadow =
  Platform.select({
    ios: {
      shadowColor: '#182B36',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
    },
    android: {
      elevation: 7,
    },
    default: {},
  }) ?? {};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CLINICAL_COLORS.background,
  },
  backgroundGradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    gap: 14,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  headerLead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  eyebrow: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  pageTitle: {
    marginTop: 2,
    color: CLINICAL_COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  headerActionRail: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  outlineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  outlineButtonText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.accentStrong,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  section: {
    marginHorizontal: 20,
    marginBottom: 22,
  },
  heroCard: {
    padding: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_COLORS.panel,
    ...cardShadow,
  },
  heroEyebrow: {
    color: CLINICAL_COLORS.accentStrong,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
  },
  heroTitle: {
    marginTop: 10,
    color: CLINICAL_COLORS.text,
    fontSize: 25,
    fontWeight: '800',
  },
  heroMeta: {
    marginTop: 8,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  heroSummary: {
    marginTop: 12,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 14,
    lineHeight: 21,
  },
  sectionHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  sectionSubtitle: {
    marginTop: 6,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  consoleStack: {
    gap: 12,
  },
  consoleCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  consoleTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  consoleItemGrid: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  consoleItemCard: {
    width: '48%',
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  consoleItemCardWide: {
    width: '100%',
  },
  consoleItemLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  consoleItemValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  consoleItemValueAccent: {
    color: CLINICAL_COLORS.accentStrong,
  },
  consoleActionRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  consoleActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  consoleActionText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  visualizationDigestCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  visualizationDigestHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  visualizationDigestHint: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  visualizationDigestList: {
    marginTop: 14,
    gap: 12,
  },
  visualizationDigestItem: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  visualizationDigestTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  visualizationDigestTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  visualizationDigestValue: {
    marginTop: 10,
    color: CLINICAL_COLORS.accentStrong,
    fontSize: 22,
    fontWeight: '800',
  },
  visualizationDigestText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  visualizationChartStack: {
    marginTop: 14,
    gap: 12,
  },
  visualizationChartCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  visualizationChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  visualizationChartHeaderMain: {
    flex: 1,
  },
  visualizationChartTitle: {
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  visualizationChartValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  visualizationChartSummary: {
    marginTop: 12,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  visualizationChartHint: {
    marginTop: 8,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  inlineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_TINTS.accentSoft,
  },
  inlineActionText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  backgroundGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  backgroundCard: {
    width: '48%',
    borderRadius: 18,
    padding: 14,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  backgroundLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  backgroundValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  summaryGrid: {
    gap: 12,
  },
  summaryCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  summaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  summaryBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  summaryBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  summaryDate: {
    marginTop: 10,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  summaryText: {
    marginTop: 10,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  toggleChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.panel,
  },
  toggleChipActive: {
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  toggleChipText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  toggleChipTextActive: {
    color: CLINICAL_COLORS.text,
  },
  card: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  focusWrap: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  focusTag: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  focusTagText: {
    color: CLINICAL_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  trendGrid: {
    gap: 12,
  },
  trendCard: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  trendCardTitle: {
    flex: 1,
    color: CLINICAL_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  trendValue: {
    marginTop: 12,
    color: CLINICAL_COLORS.accentStrong,
    fontSize: 24,
    fontWeight: '800',
  },
  trendSummary: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  chart: {
    borderRadius: 16,
  },
  chartWrap: {
    marginTop: 12,
    marginHorizontal: -2,
    borderRadius: 16,
    overflow: 'hidden',
    alignItems: 'center',
  },
  chartEmpty: {
    marginTop: 12,
    minHeight: 100,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLINICAL_TINTS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.borderSubtle,
  },
  timelineWrap: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineRail: {
    width: 18,
    alignItems: 'center',
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: CLINICAL_COLORS.accentStrong,
    marginTop: 8,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    marginTop: 6,
    marginBottom: -10,
    backgroundColor: CLINICAL_TINTS.accentBorder,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 18,
  },
  timelineHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  timelineTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  timelineTagText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  timelineTime: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  timelineTitle: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  timelineText: {
    marginTop: 8,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  reportGrid: {
    gap: 12,
  },
  reportHeroCard: {
    marginTop: 6,
    padding: 18,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
    backgroundColor: CLINICAL_COLORS.panel,
    ...cardShadow,
  },
  reportStatGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  reportStatCard: {
    flex: 1,
    minHeight: 88,
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(248, 242, 234, 0.78)',
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  reportStatValue: {
    color: CLINICAL_COLORS.text,
    fontSize: 24,
    fontWeight: '800',
  },
  reportStatLabel: {
    marginTop: 10,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  reportHeroMeta: {
    marginTop: 14,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  categoryFilterWrap: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
  },
  categoryChipActive: {
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  categoryChipText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  categoryChipTextActive: {
    color: CLINICAL_COLORS.text,
  },
  categoryChipCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
    alignItems: 'center',
  },
  categoryChipCountActive: {
    backgroundColor: 'rgba(63, 122, 112, 0.14)',
  },
  categoryChipCountText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  categoryChipCountTextActive: {
    color: CLINICAL_COLORS.text,
  },
  reportManagerList: {
    marginTop: 14,
    gap: 14,
  },
  reportManagerCard: {
    borderRadius: 26,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    ...cardShadow,
  },
  reportManagerHeader: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'flex-start',
  },
  reportIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportManagerHeaderMain: {
    flex: 1,
  },
  reportBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  reportCategoryBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.accentSoft,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.accentBorder,
  },
  reportCategoryBadgeText: {
    color: CLINICAL_COLORS.text,
    fontSize: 11,
    fontWeight: '700',
  },
  reportTypeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: CLINICAL_TINTS.neutralSoft,
  },
  reportTypeBadgeText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  reportStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(63, 122, 112, 0.10)',
  },
  reportStatusBadgeText: {
    color: CLINICAL_COLORS.accentStrong,
    fontSize: 11,
    fontWeight: '700',
  },
  reportManagerTitle: {
    marginTop: 10,
    color: CLINICAL_COLORS.text,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '800',
  },
  reportDateRow: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 10,
  },
  reportDateCard: {
    flex: 1,
    borderRadius: 18,
    padding: 12,
    backgroundColor: CLINICAL_TINTS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.borderSubtle,
  },
  reportDateLabel: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 11,
    letterSpacing: 0.3,
  },
  reportDateValue: {
    marginTop: 8,
    color: CLINICAL_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  reportManagerSummary: {
    marginTop: 14,
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  reportFileText: {
    marginTop: 10,
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
  },
  reportActionRow: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 10,
  },
  reportPrimaryAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: CLINICAL_COLORS.accentStrong,
  },
  reportPrimaryActionText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  reportGhostAction: {
    minWidth: 108,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(212, 106, 84, 0.10)',
    borderWidth: 1,
    borderColor: CLINICAL_TINTS.dangerBorder,
  },
  reportGhostActionText: {
    color: CLINICAL_COLORS.danger,
    fontSize: 13,
    fontWeight: '700',
  },
  stateWrap: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: CLINICAL_COLORS.panel,
    borderWidth: 1,
    borderColor: CLINICAL_COLORS.border,
    alignItems: 'center',
    gap: 12,
  },
  stateText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyText: {
    color: CLINICAL_COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: 'rgba(248, 242, 234, 0.76)',
  },
  loadingText: {
    color: CLINICAL_COLORS.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
});
